version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/bread-sheet-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
